readme

diff --git a/sigchecker b/sigchecker
--- a/sigchecker
+++ b/sigchecker
@@ -9,7 +9,7 @@
 #   gpg --print-md SHA512 file
 #
 
-
+EXIT_CODE=0
 for FILE in `ls *.gz *.dmg *.zip` ; do
 
 	echo ""
@@ -24,6 +24,7 @@ for FILE in `ls *.gz *.dmg *.zip` ; do
 		echo "... matches"
 	else 
 		echo "   *** does not match"
+		EXIT_CODE=1
 	fi
 
 	SHA512_ACTUAL=`shasum -a 512 $FILE |perl -n -e 's/^([[:xdigit:]]+)\s.+$/\1/; print "$_\n"' | tr [a-z] [A-Z]`
@@ -35,6 +36,7 @@ for FILE in `ls *.gz *.dmg *.zip` ; do
 		echo "... matches"
 	else 
 		echo "   *** does not match"
+		EXIT_CODE=1
 	fi
 
 	echo "Checking signature...."
@@ -43,6 +45,15 @@ for FILE in `ls *.gz *.dmg *.zip` ; do
 		echo "... valid"
 	else 
 		echo "*** INVALID"
+		EXIT_CODE=1
 	fi
-
 done
+
+if [ "$EXIT_CODE" == "0" ] ; then 
+	echo "All checks have passed"
+else 
+	echo "*** Some checks have failed"
+	EXIT_CODE=1
+fi
+
+exit $EXIT_CODE
